steps:
  - name: 'gcr.io/cloud-builders/gsutil'
    args: [
       'cp',
       'gs://finsyn-ml-data/models/model.h5',
       'model.h5'
       ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t',
      'eu.gcr.io/${PROJECT_ID}/${REPO_NAME}:${REVISION_ID}',
      '.'
      ]
images: [
  'eu.gcr.io/${PROJECT_ID}/${REPO_NAME}:${REVISION_ID}'
  ]



