steps:
  - name: 'gcr.io/cloud-builders/gsutil'
    args: [
       'cp',
       '-r',
       # change this once a new, hopefully better model has been trained 
       'gs://finsyn-ml-data/2018-09-02/*',
       './'
       ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-f',
      'docker/Dockerfile.dist',
      '-t',
      'eu.gcr.io/${PROJECT_ID}/${REPO_NAME}:${REVISION_ID}',
      '.'
      ]
images: [
  'eu.gcr.io/${PROJECT_ID}/${REPO_NAME}:${REVISION_ID}'
  ]



