FROM gw000/keras

WORKDIR /opt/forecaster/ 

RUN pip install \
      pandas \
      sklearn

ENV TF_CPP_MIN_LOG_LEVEL 2
ENV GOOGLE_APPLICATION_CREDENTIALS /opt/forecaster/key.json

ENTRYPOINT ["python"]
